/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "APILNE",
            "endpoint": "https://j7n30xspj7.execute-api.sa-east-1.amazonaws.com/dev",
            "region": "sa-east-1"
        },
        {
            "name": "AdminQueries",
            "endpoint": "https://96rp2do3hd.execute-api.sa-east-1.amazonaws.com/dev",
            "region": "sa-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "sa-east-1:9dcdc734-3487-420a-89b4-753b936364d2",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_YHdpHJB59",
    "aws_user_pools_web_client_id": "4r46obsoj2acvs2milrhu7b06u",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "sa-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "Prenda-dev",
            "region": "sa-east-1"
        }
    ]
};


export default awsmobile;
